#!/bin/sh

bspc config border_width        2
bspc config window_gap         12

bspc config split_ratio         0.52
bspc config borderless_monocle  false
bspc config gapless_monocle     true
bspc config focus_by_distance   false

bspc config focused_border_color "#00ccFF"

bspc monitor -d 1 2 3 4 5

bspc rule -a Gimp desktop=^8 follow=on floating=on
bspc rule -a mplayer2 floating=on
bspc rule -a furxvt floating=on
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a mednafen manage=on border=on
bspc rule -a pavucontrol floating=on


bspc config top_padding 27
bspc config bottom_padding 0

nitrogen --restore
xflux -z 30309 -k 2000
setxkbmap -option caps:super

xscreensaver -no-splash &
nm-applet &
owncloud &
compton &
tint2 &
conky &
